# Generated by Django 2.2.7 on 2019-11-09 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20191109_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 9, 36, 6, 408997, tzinfo=utc)),
        ),
    ]
