# Generated by Django 2.2.7 on 2019-11-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20191109_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
